version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn BaseApp.manager:app --host 0.0.0.0 --reload
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgresqldb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres