"""user table update

Revision ID: ecdd14e249f6
Revises: 3458771c02da
Create Date: 2021-06-10 11:40:49.552022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdd14e249f6'
down_revision = '3458771c02da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_delete')
    # ### end Alembic commands ###
